# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets :
        thumb :
            quality : 50
            filters :
                thumbnail:
                    size : [160, 130]
                    mode:   outbond
        medium :
            quality : 1000
            filters :
                thumbnail:
                    size : [800, 300]
                    mode:   outbond               
