vich_uploader:
    db_driver: orm

    mappings:
        articles_images:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

#    mappings:
#        featured_images:
#            uri_prefix: '%app.path.featured_images%'
#            namer: Vich\UploaderBundle\Naming\UniqidNamer
#            upload_destination: '%kernel.project_dir%/public%app.path.featured_images%'
