vich_uploader:
    db_driver: orm

    mappings:
        articles_images:
            uri_prefix: '%app.path.articles_images%'
#           namer: Vich\UploaderBundle\Naming\UniqIdNamer
            upload_destination: '%kernel.project_dir%/public%app.path.articles_images%'